### PR TITLE
use new permission system

### LINKED ISSUE #3: Session expires immediately on login
When I login with a confirmed and created user an interface flashes really quickly and I'm immediately logged out with an error by bitwarden - "Logged Out. Your login session has expired."

How can I debug this if this is a problem with js/css from yunohost?

I tried with safe-mode in FF and with completly fresh install of chromium-browser.

### PR DESCRIPTION
**Pull request by kay0u**
## Problem
- *Fix #3 close #48*

## Solution
- *Use new permission system*

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [x] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/bitwarden_ynh%20PR109%20(yalh76)/)

### CODE REVIEW

**Comment by Thovi98** [comment]
Tested and approuved :tada: 
Works for new install, didn't try to upgrade, but with this PR, session doesn't expire after login ! Thanks a lot :partying_face:

**Review by yalh76 — APPROVED** [review]
Thanks a lot.... a lot ... a lot ... Will help me for other apps ^^

I will just wait for package check results

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by alexAubin** [comment]
Test failed in multi instance only because of disk quota, I think it's good enough ...

**Review by alexAubin — APPROVED** [review]
LGTM

**Review by yalh76 — APPROVED** [review]

**Comment by yalh76** [comment]
# Own CI results for buster
image

**Pull request merged**
