### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *package_check error*

## Solution
- *add sleep time*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/bitwarden_ynh%20PR15%20(yalh76)/)

### CODE REVIEW

**Comment by kay0u** [comment]
Are you sure the `line match` is the good one? (I can't dig into it for now sry)

**Comment by yalh76** [comment]
> 
> 
> Are you sure the `line match` is the good one? (I can't dig into it for now sry)

yes pretty sure, I took it from another good packager :p

https://github.com/YunoHost-Apps/gitlab_ynh/blob/3eab332dc15a369c368a94216db8c81db2d171b2/scripts/install#L189-L197

**Comment by kay0u** [comment]
I was talking about the argument `line_match`, if package check get a 502 error, it may be because the app has not finished to starting after the line "Rocket has launched from" in logs

**Comment by yalh76** [comment]
> 
> 
> I was talking about the argument `line_match`, if package check get a 502 error, it may be because the app has not finished to starting after the line "Rocket has launched from" in logs

Misunderstanding ^^ 

Using `journalctl -u bitwarden -fe` the last log is: `Rocket has launched from http://127.0.0.1 # Enable this to test mobile app:8095`

**Pull request merged**
